[dev]
  command = "npm run dev"
  framework = "#custom"
  targetPort = 8080
  port = 3000  


[[redirects]]
  from = "/api/*"
  to = "http://www.sappun.co.kr/:splat"
  status = 200
  force = true


[build]
  functions = "functions"
